version: '3.7'

services:
  db-server:
    image: mysql:5.7-oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db_laravel
      - MYSQL_ROOT_PASSWORD=Ch4ng3me!@
    volumes:
      - ./db:/var/lib/mysql
    network_mode: host