replicaCount: 1
image:
  repository: mrfzy00/crud_laravel_api-sre-test-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: laravel-app
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50


ingress:
  enabled: false
  annotations: {}
  hosts:
  - host: chart-example.local
    paths: ["/"]
  tls: []

appKey:
  secretName: laravel-minikube-app-key
  secretKey: APP_KEY

database:
  enabled: true
  version: "5.7-oracle"
  type: mysql
  name: laraveldb
  user: root
  rootPassword: "Ch4ng3me!@"

prometheus:
  enabled: true
  alertmanager:
    enabled: true
  serverFiles:
    prometheus.yml:
      global:
        scrape_interval: 15s
      scrape_configs:
      - job_name: 'laravel-app'
        static_configs:
        - targets: ['laravel-app:80']

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer
  dashboards:
    default:
    - name: 'Laravel App Metrics'
