apiVersion: batch/v1
kind: Job
metadata:
  name: stress-job
spec:
  template:
    metadata:
      name: stress-pod
    spec:
      restartPolicy: OnFailure
      containers:
      - name: stress-container
        image: debian
        command: ["/bin/sh", "-c"]
        args:
        - "apt-get update && apt-get install -y stress && stress --cpu 2 && stress --vm 2 --vm-bytes 128M && sleep 300"
  backoffLimit: 4
