name: Laravel Docker Image CI - DEV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: api-laravel-crud/
      run: docker build . --file Dockerfile --tag ${{secrets.IMAGE_NAME}}:latest
    
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PAT}}

    - name: Push to registry docker
      working-directory: api-laravel-crud/
      run: docker push ${{secrets.DOCKER_USERNAME}}/${{secrets.IMAGE_NAME}}:latest
